# Makefile

all: pa2 head tail cat cp mv rm pwd

CC = gcc

pa2: pa2.c
	$(CC) -o $@ $<

head: head.c
	$(CC) -o $@ $<
tail: tail.c
	$(CC) -o $@ $<
cat: cat.c
	$(CC) -o $@ $<
cp: cp.c
	$(CC) -o $@ $<
mv: mv.c
	$(CC) -o $@ $<
rm: rm.c
	$(CC) -o $@ $<
pwd: pwd.c
	$(CC) -o $@ $<

clean:
	rm pa2 head tail cat cp mv rm pwd